### ISSUE TITLE
Suggestions for GCP hosting deployment guide

### ISSUE THREAD

**Issue by jovezhong** [n8n-io/n8n-docs#3191]
Greetings,

I just set up n8n on GKE by following https://docs.n8n.io/hosting/installation/server-setups/google-cloud/

The doc source code at:
https://github.com/n8n-io/n8n-docs/blob/main/docs/hosting/installation/server-setups/google-cloud.md

A few suggestions:

# Postgres
Since we are on GCP, there should be an option to use the managed postgres on GCP. Today the guide and n8n-kubernetes-hosting repo shows how to deploy the postgres in the same namespace. I'd suggest listing those 2 options. For me, we already have a Postgres in the same GCP project (other project is okay). What I do is to delete those 5 postgres-*.yaml and update n8n-deployment.yaml to set the PG host/port/user/password.

# SSL
At the end of the guide, it mentioned the DNS setup. But since https is highly recommended, I think we should add docs to setup HTTPS.. Otherwise, when I access the port using http, the web UI shows secure cookie is required and I cannot continue the setup.

How to set up the HTTPS on GKE:

1) create a managed cert, such as

```yaml
apiVersion: networking.gke.io/v1
kind: ManagedCertificate
metadata:
  name: n8n.my.com
  namespace: n8n
spec:
  domains:
    - n8n.my.com
```

apply this yaml and it can take 10-30min to get the cert provisioned.

2) Create a static IP

```bash
gcloud compute addresses create n8n --project=my-project n8n --global
```

3) create a ingress

```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: n8n-ingress
  namespace: n8n
  annotations:
    kubernetes.io/ingress.global-static-ip-name: "n8n"
    networking.gke.io/managed-certificates: "n8n.my.com"
spec:
  rules:
    - host: n8n.my.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: n8n
                port:
                  number: 5678
```
apply the change

# Upgrade
Also better to show how to upgrade n8 version in GKE.
By default the latest one is used and when you see a warning to upgrade to new version in web UI, you can run this

```
kubectl set image deployment/n8n n8n=n8nio/n8n:1.95.0 -n n8n
```

Hope it makes sense. Thanks for the great open-source project.
